### ISSUE TITLE
console.log messages during tests

### ISSUE THREAD

**Issue by canadaduane** [gohyperr/hecs#30]
Perhaps we could add a way to suppress these messages during tests?

<img width="710" alt="image" src="https://user-images.githubusercontent.com/129/99588384-bb162500-29a7-11eb-8fec-4cec0b584347.png">

```
console.log
    hecs: registered plugin 'root'

      at World.registerPlugin (../../tmp/hecs/packages/hecs/dist/hecs.js:1:24562)

  console.log
    hecs: using 0 bit archetype ids

      at ArchetypeManager.init (../../tmp/hecs/packages/hecs/dist/hecs.js:1:13344)
```

**Comment by ashconnell** [comment]
They're useful but i agree they're noisy in tests. I'm not sure of an easy way to suppress them. Any ideas?

**Comment by canadaduane** [comment]
What do you think of a library like https://www.npmjs.com/package/debug ?
